### ISSUE TITLE
Usage in Next JS

### ISSUE THREAD

**Issue by taaha827** [tkey/tkey#161]
Hey guys, So I was trying to use @tkey/web-storage for storage and retrieval of shares for keys, i was able to successfully implement it in a react solution, but when I was trying to implement it in Next JS based solution, I came across an issue where the webstorage module was not able to access the window object. I tried many things such as not using server side rendering for the component, disabling dynamic loading in next js, waiting to render the component until the window object was defined but it was the exact error every time.
Here is the error message
<img width="1507" alt="Screen Shot 2022-08-18 at 2 24 03 PM" src="https://user-images.githubusercontent.com/38415905/185478835-9679e061-c395-4f68-83d2-b82eae6731f3.png">

**Comment by sebastianupr** [comment]
You can to use dynamic import, can be use [next dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import) o with native dynamic import API like:

`
if (typeof window !== 'undefined') {
  const WebStorageModule = (await import('@tkey/web-storage')).default
  // Rest of code
} 
 `

**Comment by br4mber** [comment]
Hey @taaha827 I'm not sure if this is still bothering you but I made a minor change to the web storage module on a forked version on tKey and it's working perfectly fine. I also tried all the things you tried, and also dynamic imports but it didn't work. Heres the repo for my forked version: [https://github.com/br4mber/c0key](url)
