### ISSUE TITLE
Reconstructed private key is not a valid key 

### ISSUE THREAD

**Issue by ckshitij** [tkey/tkey#192]
I have created an app using tkey sdk, where I have used the default shares which are torus-login(Custom verifier) and local web share.
So when a user onboarding first-time at the platform the default two shares would be created and then the private key will be reconstructed. But I have observed for some users the constructed key is not the valid private key, one character was missing in all the cases.
I'm not sure why this is happening, Could anyone help me with the same?

**Comment by chaitanyapotti** [comment]
This is acceptable behaviour. You can just prepend the key with 0's at the beginning

`privKey.padStart(64, '0')`
