### ISSUE TITLE
Extended tKey SDK for use with NextJS

### ISSUE THREAD

**Issue by br4mber** [tkey/tkey#194]
Hi guys, 

I've recently been playing around with using tKey in a NextJS project, and was running into issues related to the Window object not being defined (issues with server side/ client side rendering). This issue was specifically with the web storage module. 

To fix this, I made a very simple change to the file `webstorage/dist/webStorage.cjs.js` file. I basically added `if(win){...}` conditions where `win = getWindow()` was used. It seems to be working perfectly. I believe this minor tweak would not affect other useage.  I'd open a PR but it seems that these files are hidden in the repo- maybe im being a noob.

Cheers.

**Comment by br4mber** [comment]
For use in my project, at the moment I've had to fork tKey and install my fork as a module. While this is fine for my usecase, I was wondering if this would be useful- since Next is a pretty popuar FW atm.

**Comment by chaitanyapotti** [comment]
Fixed in #196
