### ISSUE TITLE
Number of network requests increases as more shares are generated, becomes too slow

### ISSUE THREAD

**Issue by crunchwrapsupreme666** [tkey/tkey#211]
Hi, I have a simple implementation using Web3Auth and tKey:

Users login via Google SSO, 3 shares are generated (only 2 are required):
- one with the Web3Auth network
- one stored on our backend
- one on the user's local storage

Upon sign out, the local storage is cleared and the local storage share is lost. 

When signing back in, the share with the Web3Auth network is retrieved after the user signs in with Google and the share on our backend is retrieved. The key is reconstructed and a third share is newly generated and stored as the new local storage share. The other local storage share is deleted.

Over time, I've noticed the login process becomes a lot slower when reconstructing the key. It seems like the tKey library is making lots of requests based on a growing number of `polyIdList` in the metadata, even though only 3 shares are active. 

This is starting to make the login unbearably slow because so many network requests are happening in the login process. 

Is there something that I'm doing wrong here? Thanks.

**Comment by ieow** [comment]
You could update your backend share with the latest share.
with this, it will skip most of the network call

After every share operate (add or delete or refresh ) you should get update backend share.

Step to get latest version share.
After the final privatekey is reconstructed.

FIrst get the share Store. (skip this if you have shareStore backup-ed)
const shareStore = tkey.shareToShareStore( share (BN) ) 

Get shareIndex
const shareIndex = shareStore.share.shareIndex

get latest share or shareStore
const latestShare = tkey.outputShare(shareIndex) 
const latestShareStore = tkey.outputShareStore(shareIndex)

update your backend share with latest share.
