### ISSUE TITLE
@tkey/react-native-storage is removed?

### ISSUE THREAD

**Issue by dungtrinh97** [tkey/tkey#228]
Hello team, I have recently implemented SSO flow for a non-custodial mobile wallet using React Native. Last couples of weeks, I have checked that the package `@tkey/react-native-storage` was available to use but today when I install it, I get not found error. Then, I check on both npm and this repo, the package does not appear in any places.

- Is there any necessary removal on this particular package?
- What if I apply it on production and the team remove the package without any notices?
- Is there any alternative for this storage module when using React Native?

Please clarify my questions because I have plan to onboard thousands of users using SSO flow, I'm expecting a better development experience. Thanks in advance.

**Comment by chaitanyapotti** [comment]
This is moved to https://github.com/tkey/tkey-react-native-storage-module
