### ISSUE TITLE
[Function] iOS in-app Safari - Is this intended to be detected as a new device?

### ISSUE THREAD

**Issue by itsinz** [tkey/tkey#44]
Situation:
Created tKey. 4 shares. Google, PW, iOS Chrome, iOS Safari
Open Telegram
Click on uniswap.tor.us
in-app safari opens
Connect wallet
Sign in Google
New login detected screen pop ups (is this intended that an in-app Safari sign in would trigger new login? Because I have already saved a share on my iOS Safari browser)

**Comment by chaitanyapotti** [comment]
This is intended. 
In-app browsers have a different scope and don't share the same localstorage as main browser
