### ISSUE TITLE
[Function] iOS Chrome - Reload uniswap to relogin, new login detected screen triggered

### ISSUE THREAD

**Issue by itsinz** [tkey/tkey#45]
Situation:
Already have 4 shares for tKey. Google set as default
Visit uniswap.tor.us
Login via Google
Logged in to Google default acc
Visit beta.tor.us
Log in to beta.tor.us
Go settings change default to tKey
Go back to uniswap.tor.us iOS Chrome window
Refresh page (thinking the default account on widget will change)
Relogin required on uniswap.tor.us
Sign in via Google
1. Pop up blocker appear --> This should not happen (Image 1)
Click on "Continue" at the popup behind
2. New login detected modal pops up -->I am using the same iOS Chrome on mobile. This should not happen. (Image 2)

IMAGE 1
![photo_2020-11-22_03-45-18](https://user-images.githubusercontent.com/53069682/99886133-2ea08680-2c75-11eb-8849-0de34f529196.jpg)

IMAGE 2
![photo_2020-11-22_03-45-13](https://user-images.githubusercontent.com/53069682/99886141-34966780-2c75-11eb-98a1-51cb3a5e32b3.jpg)

**Comment by chaitanyapotti** [comment]
Changing default doesn't change the selected address.
ios chrome doesn't support session storage for iframe and hence every refresh requires you to login again inside a dapp
