### ISSUE TITLE
[Function] Unable to relogin to uniswap after disconnecting

### ISSUE THREAD

**Issue by itsinz** [tkey/tkey#47]
Situation
Login to uniswap with Google
Signed in to Google account
Disconnect wallet
Connect wallet again
Error (Image 1)
unable to re-login (Image 2: Refer to inspect details below)

IMAGE 1
![photo_2020-11-22_03-53-34](https://user-images.githubusercontent.com/53069682/99886302-665bfe00-2c76-11eb-9a61-899ab0ac25c2.jpg)

IMAGE 2
![photo_2020-11-22_03-53-37](https://user-images.githubusercontent.com/53069682/99886306-6eb43900-2c76-11eb-8c15-344aad4f10a7.jpg)

**Comment by chaitanyapotti** [comment]
Issue in web3-react code.
Fixed
