### ISSUE TITLE
Allow custom metadata to be added to device share

### ISSUE THREAD

**Issue by FSM1** [tkey/tkey#79]
Currently when a device share is created, the data stored about the device is often quite vague (all Chromium based browsers are reported as chrome for instance). Adding a simple text property on the share metadata would allow the user to name the device when saving a device share. Preferrably, this piece of data should be editable by the user, so that the shares could be easily renamed.

**Comment by chaitanyapotti** [comment]
This is possible to do.

```ts
await tKey.updateShareDescription(deviceShareIndex, JSON.stringify(oldShareDescription), JSON.stringify(newShareDescription), true);
```

The share descriptions can be any object.
